version: '3.8'
services:
  backend:
    build: backend/.
    volumes:
      - ./backend:/app
    ports: 
      - 3000:3000
    restart: always
    depends_on:
      - mongo
  mongo:
    image: mongo:6-jammy
    ports:
      - 27017:27017
    restart: always
    volumes:
      - db-data:/data/db
  frontend:
    build: frontend/.
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./frontend/:/app
    depends_on:
      - backend
volumes:
  db-data:
